version: '3'
services:
  app:
    image: eclipse-temurin:17-jdk-focal
    container_name: springboot-app
    ports:
      - "8082:8080"
    environment:
      - DATABASE_HOST=dpg-cja2eqtm2m9c73b5a2k0-a.oregon-postgres.render.com
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=WqFVnZPGiCKvuWzqS0lBM3jIJruJY0tx
      - DATABASE_DB_NAME=my_db_jiyn
      - DATABASE_SCHEMA_NAME=blogorama
    volumes:
      - ./build/libs/BlogoramaApi-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: [ "java", "-jar", "/app/app.jar" ]

